{{- if and .Values.postStart.enabled (not .Values.postStart.secretRefName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-as.fullname" . }}-poststart
type: Opaque
data:
  configure.sh: |
    {{- if .Values.postStart.customScript }}
    {{ .Values.postStart.customScript | b64enc | indent 4 }}
    {{- else }}
    {{ .Files.Get "scripts/configure.sh" | b64enc | indent 4 }}
    {{- end }}
{{- end }}
