apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn-as.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "openvpn-as.name" . }}
  ports:
    - port: {{ .Values.service.ports.admin }}
      targetPort: admin-gui
      protocol: TCP
      name: admin-gui
    - port: {{ .Values.service.ports.tcp }}
      targetPort: vpn-tcp
      protocol: TCP
      name: vpn-tcp
    - port: {{ .Values.service.ports.udp }}
      targetPort: vpn-udp
      protocol: UDP
      name: vpn-udp
